bd_app_sl_homepage:
    path:     /
    defaults: { _controller: BDAppSLBundle:Default:index }

bd_app_showpage:
    path:     /show
    defaults: { _controller: BDAppSLBundle:Default:show }

#bd_app_req:
#  pattern: /request_builder/
#  defaults: { _controller: BDAppSLBundle:Request_builder:req }
