parameters:
#    bd_app_sl.example.class: BDApp\SLBundle\Example

services:
#    bd_app_sl.example:
#        class: %bd_app_sl.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
